stages:
  build
  deploy
  test

variables:
  MY_VAR: $CI_PROJECT_NAME  # Use a dynamic variable instead of hardcoded value

build:
  stage: build
  script:
    - echo "Building the project for you..."
    - sleep 10
    - echo "I built it!"
  artifacts:
    paths:
      - build_output/

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - ssh $DEPLOY_SERVER "rm -rf /var/www/html/"  # Use a variable for the server
    - sftp $DEPLOY_SERVER:/var/www/html/ <<< $SSH_PASSWORD  # Use SFTP instead of SCP
    - echo "Deployment is done!"
  only:
    - main

test:
  stage: test
  script:
    - echo "Running tests..."
    - sleep 5
    - echo "Tests are done!"
  when: on_success  # Run tests automatically on success

variables:
  DEPLOY_SERVER: $CI_PROJECT_NAMESPACE  
  SSH_PASSWORD: $CI_PROJECT_PASSWORD 
