stages:
  - build
  - test
  - deploy

variables:
  MY_VAR: "Bad CI/CD practice"

build:
  stage: build script:
    - echo "Building the project for you..."
    - sleep 10
    - echo "I built it!"
  artifacts:
    paths:
      - build_output/

test: 
  stage: test script:  # Исправлено с 'skript' на 'script'
    - echo "Running tests..."
    - sleep 5
    - echo "Tests are done!"
  when: manual  # Вы можете запускать этот этап вручную

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - ssh root@my_server "rm -rf /var/www/html/*"
    - scp build_output/* root@my_server:/var/www/html/
    - echo "Deployment is done!"
  only:
    - main
